#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# Amadeus Backend Setup Script
# Automates: secret generation, dependency install, Playwright browser,
# and .env bootstrapping for new deployments.
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$BACKEND_DIR/.env"

# ── Helpers ──────────────────────────────────────────────────────────

rand_hex() { openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | xxd -p | tr -d '\n'; }

info()  { printf "\033[1;34m[setup]\033[0m %s\n" "$*"; }
ok()    { printf "\033[1;32m[setup]\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m[setup]\033[0m %s\n" "$*"; }
err()   { printf "\033[1;31m[setup]\033[0m %s\n" "$*" >&2; }

# ── 1. Node.js check ────────────────────────────────────────────────

if ! command -v node &>/dev/null; then
  err "Node.js is not installed. Please install Node.js >= 20 first."
  exit 1
fi

NODE_MAJOR=$(node -e 'console.log(process.versions.node.split(".")[0])')
if [ "$NODE_MAJOR" -lt 20 ]; then
  err "Node.js >= 20 required (found v$(node -v)). Please upgrade."
  exit 1
fi
ok "Node.js $(node -v) detected"

# ── 2. npm install ──────────────────────────────────────────────────

info "Installing backend dependencies..."
cd "$BACKEND_DIR"
npm install --production 2>&1 | tail -3
ok "Dependencies installed"

# ── 3. Playwright Chromium ──────────────────────────────────────────

info "Installing Playwright Chromium (headless browser for Twitter/X tracking)..."
npx playwright install chromium 2>&1 | tail -5
ok "Playwright Chromium installed"

# ── 4. .env bootstrapping ──────────────────────────────────────────

if [ -f "$ENV_FILE" ]; then
  info "Existing .env found — checking for missing required secrets..."

  # Ensure AUTH_SALT exists
  if ! grep -q '^AUTH_SALT=' "$ENV_FILE"; then
    SALT=$(rand_hex 32)
    echo "" >> "$ENV_FILE"
    echo "AUTH_SALT=$SALT" >> "$ENV_FILE"
    ok "Generated AUTH_SALT and appended to .env"
  else
    ok "AUTH_SALT already set"
  fi

  # Ensure JWT_SECRET exists and isn't a placeholder
  JWT=$(grep '^JWT_SECRET=' "$ENV_FILE" | cut -d= -f2-)
  if [ -z "$JWT" ] || [ "$JWT" = "replace_me_random_secret" ] || [ "$JWT" = "change-me-to-a-64-char-random-string" ]; then
    NEW_JWT=$(rand_hex 32)
    if grep -q '^JWT_SECRET=' "$ENV_FILE"; then
      sed -i.bak "s|^JWT_SECRET=.*|JWT_SECRET=$NEW_JWT|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    else
      echo "JWT_SECRET=$NEW_JWT" >> "$ENV_FILE"
    fi
    ok "Generated secure JWT_SECRET"
  else
    ok "JWT_SECRET already set"
  fi

  # Ensure CORS_ORIGIN isn't wildcard in production
  CORS=$(grep '^CORS_ORIGIN=' "$ENV_FILE" | cut -d= -f2- || true)
  NODE_ENV=$(grep '^NODE_ENV=' "$ENV_FILE" | cut -d= -f2- || true)
  if [ "$NODE_ENV" = "production" ] && [ "$CORS" = "*" ]; then
    warn "CORS_ORIGIN=* in production — update to your domain (e.g. https://your-domain.com)"
  fi

  # Set X_PLAYWRIGHT_STORAGE_STATE_PATH if not set
  if ! grep -q '^X_PLAYWRIGHT_STORAGE_STATE_PATH=' "$ENV_FILE"; then
    DEFAULT_SESSION="$HOME/.playwright/x-session.json"
    echo "" >> "$ENV_FILE"
    echo "# Twitter/X Playwright session (run setup:x-session on a machine with a browser)" >> "$ENV_FILE"
    echo "X_PLAYWRIGHT_STORAGE_STATE_PATH=$DEFAULT_SESSION" >> "$ENV_FILE"
    ok "Set X_PLAYWRIGHT_STORAGE_STATE_PATH=$DEFAULT_SESSION"
  else
    ok "X_PLAYWRIGHT_STORAGE_STATE_PATH already set"
  fi

else
  info "No .env found — generating from template..."

  if [ -f "$BACKEND_DIR/.env.example" ]; then
    cp "$BACKEND_DIR/.env.example" "$ENV_FILE"
  else
    err ".env.example not found. Please create backend/.env manually."
    exit 1
  fi

  # Replace placeholders with secure random values
  ADMIN_TOKEN=$(rand_hex 24)
  JWT_SECRET=$(rand_hex 32)
  AUTH_SALT=$(rand_hex 32)

  sed -i.bak "s|replace_me_admin_token|$ADMIN_TOKEN|" "$ENV_FILE"
  sed -i.bak "s|replace_me_random_secret|$JWT_SECRET|" "$ENV_FILE"
  rm -f "$ENV_FILE.bak"

  # Append AUTH_SALT (not in .env.example yet)
  echo "" >> "$ENV_FILE"
  echo "# Auth salt (auto-generated by setup.sh)" >> "$ENV_FILE"
  echo "AUTH_SALT=$AUTH_SALT" >> "$ENV_FILE"

  # Set Playwright session path
  DEFAULT_SESSION="$HOME/.playwright/x-session.json"
  echo "" >> "$ENV_FILE"
  echo "# Twitter/X Playwright session" >> "$ENV_FILE"
  echo "X_PLAYWRIGHT_STORAGE_STATE_PATH=$DEFAULT_SESSION" >> "$ENV_FILE"

  ok "Generated .env with secure secrets"
  warn "Edit $ENV_FILE to configure database, storage, and API keys"
  echo ""
  echo "  Generated credentials:"
  echo "    ADMIN_TOKEN = $ADMIN_TOKEN"
  echo "    JWT_SECRET  = (64-char hex, stored in .env)"
  echo "    AUTH_SALT   = (64-char hex, stored in .env)"
  echo ""
  warn "Save ADMIN_TOKEN — you'll need it for admin login if using token auth."
fi

# ── 5. Validate startup ────────────────────────────────────────────

info "Validating backend can load..."
cd "$BACKEND_DIR"
if node -e "process.env.AUTH_ENABLED='false'; require('./src/config');" 2>/dev/null; then
  ok "Config loads successfully"
else
  warn "Config validation failed — check your .env file"
fi

# ── 6. Twitter/X session hint ───────────────────────────────────────

echo ""
info "Twitter/X tracker setup (optional):"
echo "  To track Twitter/X paper posts, you need a logged-in browser session."
echo "  On a machine with a display (Mac/Windows/Linux desktop):"
echo ""
echo "    cd backend && npm run setup:x-session"
echo ""
echo "  This opens a browser, you log into X, and it saves + uploads the session."
echo "  On headless servers, upload the session file via the Tracker UI instead."
echo ""

ok "Setup complete!"
