#!/usr/bin/env bash

# Unified deployment script.
# Reads deployment profile generated by scripts/install.sh when available.
#
# Usage:
#   ./scripts/deploy.sh profile
#   ./scripts/deploy.sh deploy
#   ./scripts/deploy.sh deploy-backend
#   ./scripts/deploy.sh deploy-frontend

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

PROFILE_FILE="${DEPLOYMENT_PROFILE_FILE:-${REPO_ROOT}/deployment.mode.generated}"

# Legacy/default behavior (remote backend only) when no profile is present.
MODE_NAME="legacy_remote_backend"
NETWORK_MODE="direct"
FRONTEND_COMPILE_ON="local"
BACKEND_COMPILE_ON="remote"
FRONTEND_DEPLOY_ON="none"
BACKEND_DEPLOY_ON="remote"
DOC_METADATA_PROVIDER="unknown"
RESEARCH_METADATA_PROVIDER="unknown"
OBJECT_STORAGE_PROVIDER="unknown"

REMOTE_HOST="${DO_SERVER_IP:-${REMOTE_HOST:-}}"
REMOTE_USER="${REMOTE_USER:-root}"
REMOTE_DIR="${REMOTE_DIR:-/var/www/auto-researcher}"
REPO_URL="${REPO_URL:-https://github.com/CurryTang/Amadeus.git}"
BRANCH="${BRANCH:-master}"

BACKEND_PM2_APP="${BACKEND_PM2_APP:-auto-reader-api}"
FRONTEND_PM2_APP="${FRONTEND_PM2_APP:-auto-reader-frontend}"
BACKEND_PORT="${BACKEND_PORT:-3000}"
FRONTEND_PORT="${FRONTEND_PORT:-4173}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

trim() {
  local value="$1"
  # shellcheck disable=SC2001
  echo "$(echo "${value}" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
}

load_profile() {
  if [[ ! -f "${PROFILE_FILE}" ]]; then
    log_warn "Profile not found at ${PROFILE_FILE}. Using legacy defaults."
    return 0
  fi

  while IFS='=' read -r raw_key raw_value; do
    [[ -z "${raw_key}" ]] && continue
    [[ "${raw_key}" =~ ^# ]] && continue
    local key value
    key="$(trim "${raw_key}")"
    value="$(trim "${raw_value:-}")"

    case "${key}" in
      MODE_NAME) MODE_NAME="${value}" ;;
      NETWORK_MODE) NETWORK_MODE="${value}" ;;
      FRONTEND_COMPILE_ON) FRONTEND_COMPILE_ON="${value}" ;;
      BACKEND_COMPILE_ON) BACKEND_COMPILE_ON="${value}" ;;
      FRONTEND_DEPLOY_ON) FRONTEND_DEPLOY_ON="${value}" ;;
      BACKEND_DEPLOY_ON) BACKEND_DEPLOY_ON="${value}" ;;
      DOC_METADATA_PROVIDER) DOC_METADATA_PROVIDER="${value}" ;;
      RESEARCH_METADATA_PROVIDER) RESEARCH_METADATA_PROVIDER="${value}" ;;
      OBJECT_STORAGE_PROVIDER) OBJECT_STORAGE_PROVIDER="${value}" ;;
    esac
  done < "${PROFILE_FILE}"

  log_info "Loaded deployment profile: ${PROFILE_FILE}"
}

require_remote_host() {
  if [[ -z "${REMOTE_HOST}" ]]; then
    log_error "Remote host is required. Set DO_SERVER_IP or REMOTE_HOST."
    exit 1
  fi
}

ssh_cmd() {
  require_remote_host
  ssh -o StrictHostKeyChecking=no "${REMOTE_USER}@${REMOTE_HOST}" "$1"
}

ensure_remote_repo() {
  require_remote_host
  ssh_cmd "
    mkdir -p '${REMOTE_DIR}'
    if [ ! -d '${REMOTE_DIR}/.git' ]; then
      git clone '${REPO_URL}' '${REMOTE_DIR}'
    fi
    cd '${REMOTE_DIR}'
    git fetch origin
    if git show-ref --verify --quiet 'refs/heads/${BRANCH}'; then
      git checkout '${BRANCH}'
    else
      git checkout -b '${BRANCH}' 'origin/${BRANCH}'
    fi
    git merge --ff-only 'origin/${BRANCH}'
  "
}

print_profile() {
  cat <<EOF
Mode: ${MODE_NAME}
Network: ${NETWORK_MODE}
Frontend compile on: ${FRONTEND_COMPILE_ON}
Backend compile on: ${BACKEND_COMPILE_ON}
Frontend deploy on: ${FRONTEND_DEPLOY_ON}
Backend deploy on: ${BACKEND_DEPLOY_ON}
Document metadata provider: ${DOC_METADATA_PROVIDER}
ResearchOps metadata provider: ${RESEARCH_METADATA_PROVIDER}
Object storage provider: ${OBJECT_STORAGE_PROVIDER}
Remote host: ${REMOTE_HOST:-<not-set>}
Remote user: ${REMOTE_USER}
Remote dir: ${REMOTE_DIR}
Branch: ${BRANCH}
EOF
}

setup_remote_server() {
  require_remote_host
  log_info "Setting up remote server ${REMOTE_USER}@${REMOTE_HOST}"
  ssh_cmd "
    apt-get update
    apt-get install -y curl git
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
    npm install -g pm2
    mkdir -p '${REMOTE_DIR}'
    mkdir -p /var/log/pm2
    if [ ! -d '${REMOTE_DIR}/.git' ]; then
      git clone '${REPO_URL}' '${REMOTE_DIR}'
    fi
  "
}

deploy_backend_local() {
  log_info "Deploying backend locally"
  cd "${REPO_ROOT}/backend"
  npm ci --production
  if command -v pm2 >/dev/null 2>&1; then
    if pm2 describe "${BACKEND_PM2_APP}" >/dev/null 2>&1; then
      pm2 restart "${BACKEND_PM2_APP}" --update-env
    else
      pm2 start src/index.js --name "${BACKEND_PM2_APP}" --cwd "${REPO_ROOT}/backend" --time
    fi
  else
    log_warn "pm2 not found locally; backend build completed but process not started."
  fi
  cd "${REPO_ROOT}"
}

deploy_backend_remote() {
  log_info "Deploying backend remotely to ${REMOTE_HOST}"
  ensure_remote_repo
  ssh_cmd "
    cd '${REMOTE_DIR}/backend'
    if ! npm ci --omit=dev --no-audit --no-fund; then
      echo 'npm ci failed (likely memory pressure), falling back to npm install --omit=dev'
      npm install --omit=dev --no-audit --no-fund
    fi
    pm2 stop '${BACKEND_PM2_APP}' 2>/dev/null || true
    pm2 delete '${BACKEND_PM2_APP}' 2>/dev/null || true
    pm2 start src/index.js --name '${BACKEND_PM2_APP}' --cwd '${REMOTE_DIR}/backend'
    pm2 save
  "
}

build_frontend_local() {
  cd "${REPO_ROOT}/frontend"
  npm ci
  npm run build
  cd "${REPO_ROOT}"
}

deploy_frontend_local_runtime() {
  log_info "Deploying frontend locally"
  build_frontend_local
  if command -v pm2 >/dev/null 2>&1; then
    if pm2 describe "${FRONTEND_PM2_APP}" >/dev/null 2>&1; then
      PORT="${FRONTEND_PORT}" pm2 restart "${FRONTEND_PM2_APP}" --update-env
    else
      if [[ -f "${REPO_ROOT}/frontend/.next/standalone/server.js" ]]; then
        PORT="${FRONTEND_PORT}" pm2 start .next/standalone/server.js --name "${FRONTEND_PM2_APP}" --cwd "${REPO_ROOT}/frontend" --time
      else
        pm2 start "npm run start" --name "${FRONTEND_PM2_APP}" --cwd "${REPO_ROOT}/frontend" --time
      fi
    fi
  else
    log_warn "pm2 not found locally; frontend build completed but process not started."
  fi
}

deploy_frontend_remote_compile_remote() {
  log_info "Deploying frontend remotely (compile on remote)"
  ensure_remote_repo
  ssh_cmd "
    cd '${REMOTE_DIR}/frontend'
    npm ci
    npm run build
    pm2 stop '${FRONTEND_PM2_APP}' 2>/dev/null || true
    pm2 delete '${FRONTEND_PM2_APP}' 2>/dev/null || true
    if [ -f .next/standalone/server.js ]; then
      PORT='${FRONTEND_PORT}' pm2 start .next/standalone/server.js --name '${FRONTEND_PM2_APP}' --cwd '${REMOTE_DIR}/frontend'
    else
      pm2 start 'npm run start' --name '${FRONTEND_PM2_APP}' --cwd '${REMOTE_DIR}/frontend'
    fi
    pm2 save
  "
}

deploy_frontend_remote_compile_local() {
  log_info "Deploying frontend remotely (compile on local, run on remote)"
  require_remote_host
  build_frontend_local

  if [[ ! -f "${REPO_ROOT}/frontend/.next/standalone/server.js" ]]; then
    log_error "Standalone output not found at frontend/.next/standalone/server.js"
    log_error "Ensure Next config has output: 'standalone' and rebuild."
    exit 1
  fi

  local bundle="/tmp/auto-reader-frontend-standalone.tgz"
  local tar_args=(.next/standalone .next/static)
  local include_public=()
  if [[ -d "${REPO_ROOT}/frontend/public" ]]; then
    include_public+=(public)
  fi
  tar_args+=("${include_public[@]}")
  COPYFILE_DISABLE=1 tar --exclude='._*' -C "${REPO_ROOT}/frontend" -czf "${bundle}" "${tar_args[@]}"
  scp "${bundle}" "${REMOTE_USER}@${REMOTE_HOST}:/tmp/auto-reader-frontend-standalone.tgz"

  ssh_cmd "
    mkdir -p '${REMOTE_DIR}/frontend'
    cd '${REMOTE_DIR}/frontend'
    tar -xzf /tmp/auto-reader-frontend-standalone.tgz
    rm -f /tmp/auto-reader-frontend-standalone.tgz
    mkdir -p .next/standalone/.next
    if [ -d .next/static ]; then
      rm -rf .next/standalone/.next/static
      cp -R .next/static .next/standalone/.next/static
    fi
    if [ -d public ]; then
      rm -rf .next/standalone/public
      cp -R public .next/standalone/public
    fi
    pm2 stop '${FRONTEND_PM2_APP}' 2>/dev/null || true
    pm2 delete '${FRONTEND_PM2_APP}' 2>/dev/null || true
    PORT='${FRONTEND_PORT}' pm2 start .next/standalone/server.js --name '${FRONTEND_PM2_APP}' --cwd '${REMOTE_DIR}/frontend'
    pm2 save
  "
}

deploy_frontend() {
  if [[ "${FRONTEND_DEPLOY_ON}" == "none" ]]; then
    log_info "Frontend deployment skipped (FRONTEND_DEPLOY_ON=none)"
    return 0
  fi

  if [[ "${FRONTEND_DEPLOY_ON}" == "local" ]]; then
    deploy_frontend_local_runtime
    return 0
  fi

  if [[ "${FRONTEND_DEPLOY_ON}" != "remote" ]]; then
    log_error "Unsupported FRONTEND_DEPLOY_ON=${FRONTEND_DEPLOY_ON}"
    exit 1
  fi

  if [[ "${FRONTEND_COMPILE_ON}" == "remote" ]]; then
    deploy_frontend_remote_compile_remote
  else
    deploy_frontend_remote_compile_local
  fi
}

deploy_backend() {
  if [[ "${BACKEND_DEPLOY_ON}" == "local" ]]; then
    deploy_backend_local
    return 0
  fi
  if [[ "${BACKEND_DEPLOY_ON}" == "remote" ]]; then
    deploy_backend_remote
    return 0
  fi
  log_error "Unsupported BACKEND_DEPLOY_ON=${BACKEND_DEPLOY_ON}"
  exit 1
}

copy_env() {
  if [[ "${BACKEND_DEPLOY_ON}" == "remote" ]]; then
    require_remote_host
    if [[ -f "${REPO_ROOT}/backend/.env" ]]; then
      scp "${REPO_ROOT}/backend/.env" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/backend/.env"
      log_info "Copied backend/.env to remote."
    else
      log_warn "backend/.env not found; skipping backend env copy."
    fi
  fi

  if [[ "${FRONTEND_DEPLOY_ON}" == "remote" ]]; then
    require_remote_host
    if [[ -f "${REPO_ROOT}/frontend/.env" ]]; then
      scp "${REPO_ROOT}/frontend/.env" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/frontend/.env"
      log_info "Copied frontend/.env to remote."
    else
      log_warn "frontend/.env not found; skipping frontend env copy."
    fi
  fi
}

restart() {
  if [[ "${BACKEND_DEPLOY_ON}" == "remote" || "${FRONTEND_DEPLOY_ON}" == "remote" ]]; then
    require_remote_host
  fi
  if [[ "${BACKEND_DEPLOY_ON}" == "local" ]]; then
    pm2 restart "${BACKEND_PM2_APP}" --update-env || true
  elif [[ "${BACKEND_DEPLOY_ON}" == "remote" ]]; then
    ssh_cmd "pm2 restart '${BACKEND_PM2_APP}' --update-env || true"
  fi

  if [[ "${FRONTEND_DEPLOY_ON}" == "local" ]]; then
    pm2 restart "${FRONTEND_PM2_APP}" --update-env || true
  elif [[ "${FRONTEND_DEPLOY_ON}" == "remote" ]]; then
    ssh_cmd "pm2 restart '${FRONTEND_PM2_APP}' --update-env || true"
  fi
}

stop() {
  if [[ "${BACKEND_DEPLOY_ON}" == "local" ]]; then
    pm2 stop "${BACKEND_PM2_APP}" || true
  elif [[ "${BACKEND_DEPLOY_ON}" == "remote" ]]; then
    ssh_cmd "pm2 stop '${BACKEND_PM2_APP}' || true"
  fi

  if [[ "${FRONTEND_DEPLOY_ON}" == "local" ]]; then
    pm2 stop "${FRONTEND_PM2_APP}" || true
  elif [[ "${FRONTEND_DEPLOY_ON}" == "remote" ]]; then
    ssh_cmd "pm2 stop '${FRONTEND_PM2_APP}' || true"
  fi
}

logs() {
  if [[ "${BACKEND_DEPLOY_ON}" == "local" ]]; then
    log_info "Local backend logs (${BACKEND_PM2_APP})"
    pm2 logs "${BACKEND_PM2_APP}" --lines 80 --nostream || true
  elif [[ "${BACKEND_DEPLOY_ON}" == "remote" ]]; then
    log_info "Remote backend logs (${BACKEND_PM2_APP})"
    ssh_cmd "pm2 logs '${BACKEND_PM2_APP}' --lines 80 --nostream || true"
  fi

  if [[ "${FRONTEND_DEPLOY_ON}" == "local" ]]; then
    log_info "Local frontend logs (${FRONTEND_PM2_APP})"
    pm2 logs "${FRONTEND_PM2_APP}" --lines 80 --nostream || true
  elif [[ "${FRONTEND_DEPLOY_ON}" == "remote" ]]; then
    log_info "Remote frontend logs (${FRONTEND_PM2_APP})"
    ssh_cmd "pm2 logs '${FRONTEND_PM2_APP}' --lines 80 --nostream || true"
  fi
}

status() {
  if [[ "${BACKEND_DEPLOY_ON}" == "local" || "${FRONTEND_DEPLOY_ON}" == "local" ]]; then
    log_info "Local PM2 status"
    pm2 status
  fi
  if [[ "${BACKEND_DEPLOY_ON}" == "remote" || "${FRONTEND_DEPLOY_ON}" == "remote" ]]; then
    log_info "Remote PM2 status"
    ssh_cmd "pm2 status"
  fi
}

health() {
  local target response
  if [[ "${BACKEND_DEPLOY_ON}" == "local" ]]; then
    target="http://127.0.0.1:${BACKEND_PORT}/api/health"
    response="$(curl -s "${target}" || echo "failed")"
  else
    require_remote_host
    target="http://127.0.0.1:${BACKEND_PORT}/api/health (via remote host ${REMOTE_HOST})"
    response="$(ssh_cmd "curl -s 'http://127.0.0.1:${BACKEND_PORT}/api/health' || echo failed")"
  fi
  if [[ "${response}" == *"ok"* ]]; then
    log_info "Backend health check passed: ${target}"
    echo "${response}" | python3 -m json.tool 2>/dev/null || echo "${response}"
  else
    log_error "Backend health check failed: ${target}"
    echo "${response}"
    exit 1
  fi
}

quick_deploy() {
  log_info "Quick deploy: backend only"
  deploy_backend
}

usage() {
  cat <<EOF
Unified deployment script

Usage: $0 <command>

Commands:
  profile           Show resolved deployment profile
  setup             Setup remote server dependencies (if any remote target)
  deploy            Deploy backend + frontend per profile
  deploy-backend    Deploy backend per profile
  deploy-frontend   Deploy frontend per profile
  quick             Quick deploy backend only
  copy-env          Copy backend/frontend .env to remote targets
  restart           Restart pm2 apps based on profile
  stop              Stop pm2 apps based on profile
  logs              Tail logs
  status            PM2 status
  health            Backend health check

Environment:
  DEPLOYMENT_PROFILE_FILE   Defaults to ${PROFILE_FILE}
  DO_SERVER_IP / REMOTE_HOST
  REMOTE_USER               Default: ${REMOTE_USER}
  REMOTE_DIR                Default: ${REMOTE_DIR}
  BRANCH                    Default: ${BRANCH}
EOF
}

main() {
  load_profile

  case "${1:-}" in
    profile)
      print_profile
      ;;
    setup)
      if [[ "${BACKEND_DEPLOY_ON}" == "remote" || "${FRONTEND_DEPLOY_ON}" == "remote" ]]; then
        setup_remote_server
      else
        log_info "No remote targets in profile; setup skipped."
      fi
      ;;
    deploy)
      deploy_backend
      deploy_frontend
      ;;
    deploy-backend)
      deploy_backend
      ;;
    deploy-frontend)
      deploy_frontend
      ;;
    quick)
      quick_deploy
      ;;
    copy-env)
      copy_env
      ;;
    restart)
      restart
      ;;
    stop)
      stop
      ;;
    logs)
      logs
      ;;
    status)
      status
      ;;
    health)
      health
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

main "${1:-}"
